# Generated by Django 3.2 on 2023-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('Brand', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Products/')),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('SellerName', models.TextField(unique=True)),
                ('Stock', models.IntegerField(default=1)),
            ],
        ),
    ]
