# Generated by Django 3.2 on 2023-12-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SellerName',
            field=models.TextField(),
        ),
    ]
